import Head from "next/head";
import Header from "../components/Header";
import Top1 from "../components/Top1";
import Banner from "../components/Banner";
import Catelogue from "../components/Catelogue";
import Featured from "../components/Featured";
import Row from "../components/Row";
import ImageRow from "../components/ImageRow";
import LatestProducts from "../components/LatestProducts";
import NewsLetter from "../components/NewsLetter";
import Footer from "../components/Footer";
import Carousel from "../components/Slider";
import { carouselData } from "../assets/productData";
import Image from "next/image";

export default function Home() {
  console.log(carouselData[0]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Top1 />
        <Header />
        <div className="max-w-[screen]">
          <Carousel>
            {carouselData.map(item => (
              <div key={item} className=" max-w-[screen]  ">
                <Banner image={item} />
              </div>
            ))}
          </Carousel>
        </div>
        <Catelogue />
        <Featured title="FEATURED PRODUCTS" />
        <Row />
        <ImageRow />
        <LatestProducts />
        <Featured title="THIS MONTH HOT" />
        <NewsLetter />
        <Footer />
      </main>
    </div>
  );
}
